substitutions:
  # Set to the other device's HA entity ids, e.g.
  #  switch.room_switch_2_button_a_state / switch.room_switch_2_button_b_state
  peer_button_a_entity: ""
  peer_button_b_entity: ""

binary_sensor:
  - platform: homeassistant
    id: peer_a_source
    entity_id: ${peer_button_a_entity}
    internal: true
    on_state:
      then:
        - lambda: 'id(peer_a_on) = id(peer_a_source).state;'
        - if:
            condition:
              lambda: 'return id(button_a_state).state || id(peer_a_on);'
            then:
              - light.turn_on: blue_led
            else:
              - light.turn_off: blue_led

  - platform: homeassistant
    id: peer_b_source
    entity_id: ${peer_button_b_entity}
    internal: true
    on_state:
      then:
        - lambda: 'id(peer_b_on) = id(peer_b_source).state;'
        - if:
            condition:
              lambda: 'return id(button_b_state).state || id(peer_b_on);'
            then:
              - switch.turn_on: red_led
            else:
              - switch.turn_off: red_led

