# Generic package for Sonoff SwitchMan M5 (1-gang, EU)
# - Modes: Local / HA only / Both (visible in HA)
# - Relay behavior: Latching / Momentary 200ms / Inching (with seconds)
# - Gestures: single (ON/OFF semantics), double (fan-out), hold (loop)
# - Offline behavior: relay-only; online resumes configured behavior
# - Indicator: Panel Backlight ON only when the followed entity (or relay if offline) is ON
#
# NOTE: Define wifi:/api:/ota: in your per-device file. This package assumes api: is present.

substitutions:
  device_name: ""
  device_friendly_name: ""

  # Entity to FOLLOW for state & indicator (defaults to our own relay)
  a_follow_entity: "switch.${device_name}_relay_a"

  # Single-press ON path (used when the followed entity is currently OFF)
  a_on_service: "switch.turn_on"       # e.g. "light.turn_on"
  a_on_entity: ""                      # e.g. "light.room_main"
  a_on_kelvin: "0"                     # optional; "0" = not sent
  a_on_brightness_pct: "0"             # optional; "0" = not sent

  # Single-press OFF path (used when the followed entity is currently ON)
  a_off_service: "switch.turn_off"     # e.g. "light.turn_off"
  a_off_entity: ""

  # Double-click fan-out (up to 3 service calls; optional)
  a_double_service: ""
  a_double_entity: ""
  a_double_service2: ""
  a_double_entity2: ""
  a_double_service3: ""
  a_double_entity3: ""
  a_double_step_pct: "0"               # for light.turn_on; "0" = not sent

  # Hold (repeats ~150ms while pressed & online; up to 3 calls; optional)
  a_hold_service: ""
  a_hold_entity: ""
  a_hold_service2: ""
  a_hold_entity2: ""
  a_hold_service3: ""
  a_hold_entity3: ""
  a_hold_step_pct: "0"                 # for light.turn_on; "0" = not sent

  # Default operating mode for this gang
  default_mode_a: "Local"              # Local | HA only | Both

logger:

# ---- Hardware mapping (Sonoff M5 1-gang EU) ----
# Button A: GPIO0
# Relay A:  GPIO23
# Panel backlight PWM: GPIO18
# Status LED: GPIO5
status_led:
  pin: GPIO5

output:
  - platform: ledc
    id: panel_pwm
    pin: GPIO18
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: panel_backlight
    name: "${device_friendly_name} Panel Backlight"
    output: panel_pwm
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s

# --- Relay A with HA-only guard + behavior shaping on ON ---
switch:
  - platform: gpio
    id: relay_a
    name: "${device_friendly_name} Relay A"
    pin: GPIO23
    on_turn_off:
      then:
        - component.update: a_effective_state
        - script.execute: update_indicator
        - if:
            condition:
              and:
                - lambda: 'return id(mode_a).state == "HA only";'
                - api.connected
            then:
              - switch.turn_on: relay_a
    on_turn_on:
      then:
        - component.update: a_effective_state
        - script.execute: update_indicator
        # Apply behavior shaping only when not HA-only (we're allowed to touch the relay)
        - if:
            condition:
              lambda: 'return id(mode_a).state != "HA only";'
            then:
              - if:
                  condition:
                    lambda: 'return id(behavior_a).state == "Momentary 200ms";'
                  then:
                    - delay: 200ms
                    - switch.turn_off: relay_a
              - if:
                  condition:
                    lambda: 'return id(behavior_a).state == "Inching";'
                  then:
                    - delay: !lambda 'return (uint32_t)(id(inching_a_secs).state * 1000);'
                    - switch.turn_off: relay_a

# --- User-configurable selects/numbers visible in HA ---
select:
  - platform: template
    id: mode_a
    name: "${device_friendly_name} – Mode A"
    options:
      - Local
      - HA only
      - Both
    optimistic: true
    restore_value: true
    initial_option: ${default_mode_a}
    entity_category: config

  - platform: template
    id: behavior_a
    name: "${device_friendly_name} – Relay A behavior"
    options:
      - Latching
      - Momentary 200ms
      - Inching
    optimistic: true
    restore_value: true
    initial_option: "Latching"
    entity_category: config

number:
  - platform: template
    id: inching_a_secs
    name: "${device_friendly_name} – Inching A (s)"
    min_value: 1
    max_value: 600
    step: 1
    initial_value: 5
    optimistic: true
    restore_value: true
    entity_category: config

esphome:
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            and:
              - api.connected
              - lambda: 'return id(mode_a).state == "HA only";'
          then:
            - switch.turn_on: relay_a
      - script.execute: update_indicator

binary_sensor:
  # Physical button
  - platform: gpio
    id: btn_a
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on_off: 30ms
    # Single click
    on_click:
      - min_length: 50ms
        max_length: 400ms
        then:
          - script.execute: a_single
    # Double click
    on_double_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - script.execute: a_double
    # Hold: start loop after 500ms; stop when released
    on_press:
      then:
        - delay: 500ms
        - if:
            condition:
              binary_sensor.is_on: btn_a
            then:
              - script.execute: a_hold_loop
    on_release:
      then:
        - script.stop: a_hold_loop

  # Dashboard-friendly state: ON when the *effective output* is ON
  # (uses followed HA entity when online; otherwise mirrors the relay)
  - platform: template
    id: a_effective_state
    name: "${device_friendly_name} Button A state"
    device_class: power
    lambda: |-
      if (id(a_state).has_state()) {
        return id(a_state).state == "on";
      }
      return id(relay_a).state;

# Follow HA entity for state & indicator (falls back to relay when HA is offline)
text_sensor:
  - platform: homeassistant
    id: a_state
    entity_id: ${a_follow_entity}
    on_value:
      then:
        - lambda: |-
            if (id(a_state).state == "on") {
              id(a_last_known_on) = true;
            } else if (id(a_state).state == "off") {
              id(a_last_known_on) = false;
            }
        - component.update: a_effective_state
        - script.execute: update_indicator

globals:
  - id: a_last_known_on
    type: bool
    restore_value: no
    initial_value: 'false'

script:
  # Indicator: backlight ON (70%) when followed entity is ON; else OFF
  # When HA state is missing (offline), we fall back to the relay state.
  - id: update_indicator
    then:
      - lambda: |-
          bool on = false;
          if (id(a_state).has_state()) {
            on = (id(a_state).state == "on");
          } else {
            on = id(relay_a).state;
          }
          if (on) {
            auto call = id(panel_backlight).turn_on();
            call.set_brightness(0.70f);
            call.perform();
          } else {
            id(panel_backlight).turn_off();
          }

  # --- Single press: decides OFF vs ON; offline = relay toggle only ---
  - id: a_single
    then:
      - if:
          condition:
            api.connected
          then:
            # Decide current state from HA (if available) else relay
            - lambda: |-
                bool is_on = id(a_last_known_on);
                if (!id(a_state).has_state()) { is_on = id(relay_a).state; }
                id(a_last_known_on) = !is_on;  // target state after this press
            # OFF path
            - if:
                condition:
                  lambda: 'return !id(a_last_known_on);'
                then:
                  - if:
                      condition:
                        lambda: 'return id(mode_a).state != "HA only";'
                      then:
                        - switch.turn_off: relay_a
                  - if:
                      condition:
                        lambda: 'return strlen("${a_off_entity}") > 0;'
                      then:
                        - homeassistant.service:
                            service: ${a_off_service}
                            data:
                              entity_id: ${a_off_entity}
            # ON path
            - if:
                condition:
                  lambda: 'return id(a_last_known_on);'
                then:
                  - if:
                      condition:
                        lambda: 'return id(mode_a).state != "HA only";'
                      then:
                        - switch.turn_on: relay_a
                  # Build service call with optional fields
                  - if:
                      condition:
                        lambda: 'return strlen("${a_on_entity}") > 0;'
                      then:
                        - if:
                            condition:
                              lambda: 'return ${a_on_kelvin} != 0 && ${a_on_brightness_pct} != 0;'
                            then:
                              - homeassistant.service:
                                  service: ${a_on_service}
                                  data:
                                    entity_id: ${a_on_entity}
                                    kelvin: !lambda 'return ${a_on_kelvin};'
                                    brightness_pct: !lambda 'return ${a_on_brightness_pct};'
                        - if:
                            condition:
                              lambda: 'return ${a_on_kelvin} != 0 && ${a_on_brightness_pct} == 0;'
                            then:
                              - homeassistant.service:
                                  service: ${a_on_service}
                                  data:
                                    entity_id: ${a_on_entity}
                                    kelvin: !lambda 'return ${a_on_kelvin};'
                        - if:
                            condition:
                              lambda: 'return ${a_on_kelvin} == 0 && ${a_on_brightness_pct} != 0;'
                            then:
                              - homeassistant.service:
                                  service: ${a_on_service}
                                  data:
                                    entity_id: ${a_on_entity}
                                    brightness_pct: !lambda 'return ${a_on_brightness_pct};'
                        - if:
                            condition:
                              lambda: 'return ${a_on_kelvin} == 0 && ${a_on_brightness_pct} == 0;'
                            then:
                              - homeassistant.service:
                                  service: ${a_on_service}
                                  data:
                                    entity_id: ${a_on_entity}
          else:
            # Offline: act as a dumb switch
            - switch.toggle: relay_a

  # --- Double click: up to 3 HA service calls; offline falls back to relay toggle ---
  - id: a_double
    then:
      - if:
          condition:
            api.connected
          then:
            - if:
                condition:
                  lambda: 'return strlen("${a_double_entity}") > 0;'
                then:
                  - if:
                      condition:
                        lambda: 'return ${a_double_step_pct} != 0;'
                      then:
                        - homeassistant.service:
                            service: ${a_double_service}
                            data:
                              entity_id: ${a_double_entity}
                              brightness_step_pct: !lambda 'return ${a_double_step_pct};'
                      else:
                        - homeassistant.service:
                            service: ${a_double_service}
                            data:
                              entity_id: ${a_double_entity}
            - if:
                condition:
                  lambda: 'return strlen("${a_double_entity2}") > 0;'
                then:
                  - homeassistant.service:
                      service: ${a_double_service2}
                      data:
                        entity_id: ${a_double_entity2}
            - if:
                condition:
                  lambda: 'return strlen("${a_double_entity3}") > 0;'
                then:
                  - homeassistant.service:
                      service: ${a_double_service3}
                      data:
                        entity_id: ${a_double_entity3}
          else:
            - switch.toggle: relay_a

  # --- Hold: loop while pressed & online; emits up to 3 service calls per tick ---
  - id: a_hold_loop
    then:
      - while:
          condition:
            and:
              - binary_sensor.is_on: btn_a
              - api.connected
          then:
            - if:
                condition:
                  lambda: 'return strlen("${a_hold_entity}") > 0;'
                then:
                  - if:
                      condition:
                        lambda: 'return ${a_hold_step_pct} != 0;'
                      then:
                        - homeassistant.service:
                            service: ${a_hold_service}
                            data:
                              entity_id: ${a_hold_entity}
                              brightness_step_pct: !lambda 'return ${a_hold_step_pct};'
                      else:
                        - homeassistant.service:
                            service: ${a_hold_service}
                            data:
                              entity_id: ${a_hold_entity}
            - if:
                condition:
                  lambda: 'return strlen("${a_hold_entity2}") > 0;'
                then:
                  - homeassistant.service:
                      service: ${a_hold_service2}
                      data:
                        entity_id: ${a_hold_entity2}
            - if:
                condition:
                  lambda: 'return strlen("${a_hold_entity3}") > 0;'
                then:
                  - homeassistant.service:
                      service: ${a_hold_service3}
                      data:
                        entity_id: ${a_hold_entity3}
            - delay: 150ms
