substitutions:
  device_friendly_name: "Switchman M5 1G"
  device_name: "switchman-m5-1g"
  device_ip: ""
  device_make: "Sonoff"
  device_model: "Switchman M5 (1-Gang)"
  package_version: "1.1.0"

  api_key: !secret api_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

  button_a_gpio: GPIO00
  relay_a_gpio: GPIO23
  led_indicator_gpio: GPIO19      # Red LED - shows button_a_state (ON = red light)
  led_status_gpio: GPIO05         # Blue LED - used for system status
  led_pwm_output_gpio: GPIO18     # PWM control for red LED brightness

  log_level: INFO
  timezone: "Europe/Tallinn"

  # Shorter GPIO debounce to reduce perceived latency
  filter_delay_on: 10ms
  filter_delay_off: 10ms

  # Multi-click timing configuration (optimized for UX)
  # Keep single snappy while preserving reliable double detection
  timing_single_click_off: OFF for at least 260ms
  timing_double_click_1: ON for at most 300ms
  timing_double_click_2: OFF for at most 250ms
  timing_double_click_3: ON for at most 300ms
  timing_double_click_4: OFF for at least 60ms

  timing_hold: ON for at least 1s
  timing_hold_repeat: 500ms

  default_mode_a: "Coupled"               # Coupled | Decoupled
  default_relay_a_target_mode: "Off"      # "On" or "Off" when HA/API is available
  min_toggle_interval_ms: 250              # ignore extra presses faster than this
  
  # Circuit breaker and debouncing settings
  circuit_breaker_reset_interval_ms: 5000  # reset circuit breaker counter after this time
  circuit_breaker_max_toggles: 3           # max toggles before circuit breaker triggers
  ha_action_cooldown_ms: 2000              # cooldown between HA service calls (increased for group stability)
  relay_sync_cooldown_ms: 100              # prevent HA-initiated loops in coupled mode
  feedback_loop_protection_ms: 5000        # prevent switch group feedback loops

  # HA service wiring (leave empty to do nothing)
  # CRITICAL: When using Home Assistant switch groups, these settings prevent feedback loops:
  # - ha_action_cooldown_ms: 2000ms (increased from 100ms) 
  # - feedback_loop_protection_ms: 5000ms (blocks calls after external changes)
  # Without proper protection, multiple switches calling the same group can cause endless flickering!
  button_a_on_service: ""
  button_a_on_entity: ""
  button_a_off_service: ""
  button_a_off_entity: ""
  button_a_double_service: ""
  button_a_double_entity: ""
  button_a_hold_service: ""
  button_a_hold_entity: ""

esphome:
  name: "${device_name}"
  friendly_name: "${device_friendly_name}"
  comment: "${device_model} by ${device_make} version ${package_version}"
  name_add_mac_suffix: false
  on_boot:
    - priority: 900.0
      then:
        - lambda: |-
            id(cpu_speed) = ESP.getCpuFreqMHz();
    # Boot sequence: Sync relay <-> button state when in Coupled mode
    # This ensures physical relay matches virtual button state after restart
    - priority: 600.0
      then:
        - if:
            condition:
              lambda: 'return id(mode_a).state == std::string("Coupled");'
            then:
              - if:
                  condition:
                    lambda: 'return id(button_a_state).state != id(relay_a).state;'
                  then:
                    - if:
                        condition:
                          lambda: 'return id(button_a_state).state;'
                        then:
                          - switch.turn_on: relay_a
                        else:
                          - switch.turn_off: relay_a

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

logger:
  level: "${log_level}"
  baud_rate: 0

wifi:
  fast_connect: false
  power_save_mode: none
  ssid: ${wifi_ssid}
  password: ${wifi_password}

ota:
  - platform: esphome
    password: ${ota_password}

api:
  encryption:
    key: ${api_key}

web_server:
  port: 80

time:
  - platform: sntp
    id: time_service
    timezone: ${timezone}

globals:
  - id: cpu_speed
    type: int
    restore_value: false
    initial_value: "0"

  - id: last_user_toggle_ms_a
    type: uint32_t
    restore_value: false
    initial_value: '0'
  
  # Script-level debouncing and feedback loop protection
  - id: last_ha_action_ms_a
    type: uint32_t
    restore_value: false
    initial_value: '0'
  
  # Feedback loop protection for switch groups
  - id: last_external_change_ms_a
    type: uint32_t
    restore_value: false
    initial_value: '0'
  
  # Circuit breaker protection
  - id: toggle_count_a
    type: int
    restore_value: false
    initial_value: '0'
  - id: circuit_breaker_start_ms_a
    type: uint32_t
    restore_value: false
    initial_value: '0'

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "IP Address"
      icon: "mdi:wan"

  - platform: template
    name: "Uptime"
    id: uptime_human
    icon: "mdi:timer-check-outline"
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

sensor:
  - platform: uptime
    name: "Uptime (s)"
    id: sensor_uptime
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(sensor_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds %= 24 * 3600;
              int hours = seconds / 3600;
              seconds %= 3600;
              int minutes = seconds / 60;
              seconds %= 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: internal_temperature
    name: "Internal Temperature"
    icon: mdi:heat-wave
    disabled_by_default: true

  - platform: template
    name: "CPU Frequency"
    icon: "mdi:speedometer"
    accuracy_decimals: 0
    unit_of_measurement: MHz
    disabled_by_default: true
    lambda: |-
      return (id(cpu_speed));
    entity_category: diagnostic

  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"

  # Virtual gesture buttons for HA integration
  # These trigger the same actions as physical multi-click/hold gestures
  - platform: template
    name: "Button A double click action"
    id: button_a_sim_double
    on_press:
      - script.execute: a_double_action

  - platform: template
    name: "Button A hold action"
    id: button_a_sim_hold
    on_press:
      - script.execute: a_hold_action

output:
  - platform: ledc
    id: pwm_output
    pin: ${led_pwm_output_gpio}
    frequency: 1000 Hz

light:
  - platform: monochromatic
    output: pwm_output
    name: "Red LED"
    id: red_led_backlight
    internal: true
    restore_mode: RESTORE_DEFAULT_OFF
    icon: 'mdi:led-outline'
    entity_category: 'config'

  - platform: status_led
    name: "Blue LED"
    id: led_status
    internal: true
    pin:
      number: ${led_status_gpio}
      inverted: true
      ignore_strapping_warning: true
    restore_mode: RESTORE_DEFAULT_OFF

switch:
  # LED BEHAVIOR (1-Gang): Red LED mirrors button_a_state
  # - button_a_state ON → Red LED ON (intentional design)
  # - This provides visual feedback for virtual button state
  - platform: gpio
    name: "LED indicator"
    id: led_indicator
    internal: true
    pin: ${led_indicator_gpio}

  # Physical relay A - controls actual load switching
  # Syncs with virtual button state in Coupled mode
  - platform: gpio
    name: "Relay A"
    id: relay_a
    pin: ${relay_a_gpio}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - switch.turn_on: led_indicator  # Always sync LED with relay
      # Prevent feedback loops: only sync button state if this was user-initiated
      - if:
          condition:
            and:
              - lambda: 'return id(mode_a).state == std::string("Coupled") && id(button_a_state).state == false;'
              - lambda: 'return (millis() - id(last_user_toggle_ms_a)) >= ${relay_sync_cooldown_ms};'  # Anti-loop protection
          then:
            - switch.turn_on: button_a_state  # Sync virtual state
    on_turn_off:
      - switch.turn_off: led_indicator  # Always sync LED with relay
      # Prevent feedback loops: only sync button state if this was user-initiated
      - if:
          condition:
            and:
              - lambda: 'return id(mode_a).state == std::string("Coupled") && id(button_a_state).state == true;'
              - lambda: 'return (millis() - id(last_user_toggle_ms_a)) >= ${relay_sync_cooldown_ms};'  # Anti-loop protection
          then:
            - switch.turn_off: button_a_state  # Sync virtual state

  # Virtual button A state - represents logical switch state
  # In Decoupled mode: independent of physical relay, only triggers HA actions
  # In Coupled mode: bidirectionally synced with physical relay
  - platform: template
    name: "Button A state"
    id: button_a_state
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - switch.turn_on: led_indicator  # Always sync LED indicator
      # Track external changes (from HA) for feedback loop protection
      - if:
          condition:
            lambda: 'return (millis() - id(last_user_toggle_ms_a)) >= 1000;'  # If >1s since user action, likely external
          then:
            - lambda: |-
                id(last_external_change_ms_a) = millis();
                ESP_LOGD("feedback", "External change detected for button_a_state ON");
      # Decoupled mode: trigger HA action only (relay stays independent)
      - if:
          condition:
            lambda: 'return id(mode_a).state == std::string("Decoupled");'
          then:
            - script.execute: a_on_action
      # Coupled mode: mirror state to physical relay
      - if:
          condition:
            lambda: 'return id(mode_a).state == std::string("Coupled") && id(relay_a).state == false;'
          then:
            - switch.turn_on: relay_a
    on_turn_off:
      - switch.turn_off: led_indicator  # Always sync LED indicator
      # Track external changes (from HA) for feedback loop protection
      - if:
          condition:
            lambda: 'return (millis() - id(last_user_toggle_ms_a)) >= 1000;'  # If >1s since user action, likely external
          then:
            - lambda: |-
                id(last_external_change_ms_a) = millis();
                ESP_LOGD("feedback", "External change detected for button_a_state OFF");
      # Decoupled mode: trigger HA action only (relay stays independent)
      - if:
          condition:
            lambda: 'return id(mode_a).state == std::string("Decoupled");'
          then:
            - script.execute: a_off_action
      # Coupled mode: mirror state to physical relay
      - if:
          condition:
            lambda: 'return id(mode_a).state == std::string("Coupled") && id(relay_a).state == true;'
          then:
            - switch.turn_off: relay_a

select:
  - platform: template
    id: mode_a
    name: "Button A mode"
    options:
      - "Coupled"
      - "Decoupled"
    optimistic: true
    restore_value: true
    initial_option: ${default_mode_a}
    entity_category: config
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(mode_a).state == std::string("Decoupled");'
            then:
              - if:
                  condition:
                    switch.is_on: button_a_state
                  then:
                    - switch.turn_on: led_indicator
                  else:
                    - switch.turn_off: led_indicator
            else:
              - if:
                  condition:
                    switch.is_on: relay_a
                  then:
                    - switch.turn_on: led_indicator
                  else:
                    - switch.turn_off: led_indicator

  # Exposed selector that defines the enforced relay state when API is connected
  - platform: template
    id: relay_a_target_mode
    name: "Relay A target mode"
    options:
      - "On"
      - "Off"
    optimistic: true
    restore_value: true
    initial_option: ${default_relay_a_target_mode}
    entity_category: config
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(relay_a_target_mode).state == std::string("On");'
            then:
              - switch.turn_on: relay_a
            else:
              - switch.turn_off: relay_a

number: []

binary_sensor:
  # Physical button A with multi-click detection
  # - Single click: immediate toggle with debouncing
  # - Double click: custom HA action
  # - Hold: repeating custom HA action with LED feedback
  - platform: gpio
    id: button_a
    internal: true
    pin:
      number: ${button_a_gpio}
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    filters:
      - delayed_on: ${filter_delay_on}
      - delayed_off: ${filter_delay_off}
    on_multi_click:
      # Double click first (prevents single from stealing)
      - timing:
          - ${timing_double_click_1}
          - ${timing_double_click_2}
          - ${timing_double_click_3}
          - ${timing_double_click_4}
        then:
          - button.press: button_a_sim_double
          # Only trigger via the exposed virtual button to avoid duplicate actions
      # Hold (repeat)
      - timing:
          - ${timing_hold}
        then:
          - while:
              condition:
                binary_sensor.is_on: button_a
              then:
                - light.toggle: led_status
                - button.press: button_a_sim_hold
                - delay: ${timing_hold_repeat}
          - light.turn_off: led_status
      # Single click last (fires quickly after release, still leaves room for double)
      - timing:
          - ON for at most 300ms
          - ${timing_single_click_off}
        then:
          # Anti-bounce protection: prevent rapid toggling
          - if:
              condition:
                lambda: 'return (millis() - id(last_user_toggle_ms_a)) >= (uint32_t) ${min_toggle_interval_ms};'
              then:
                # Circuit breaker: prevent relay damage from excessive switching
                - lambda: |-
                    id(last_user_toggle_ms_a) = millis();
                    // Circuit breaker logic - track toggles over time window
                    uint32_t now = millis();
                    if ((now - id(circuit_breaker_start_ms_a)) > ${circuit_breaker_reset_interval_ms}) {
                      // Reset counter after time window expires
                      id(toggle_count_a) = 0;
                      id(circuit_breaker_start_ms_a) = now;
                    }
                    id(toggle_count_a)++;
                    if (id(toggle_count_a) > ${circuit_breaker_max_toggles}) {
                      ESP_LOGW("switch", "Circuit breaker triggered for channel A - too many toggles");
                      return; // Skip this toggle to protect relay
                    }
                # Mode-dependent behavior - FEEDBACK LOOP PROTECTION:
                # COUPLED: Physical button controls both relay AND HA services (with protection)  
                # DECOUPLED: Physical button only controls HA actions (no relay)
                - if:
                    condition:
                      lambda: 'return id(mode_a).state == std::string("Coupled");'
                    then:
                      # Coupled mode: toggle relay and call HA service (but with enhanced protection)
                      - if:
                          condition:
                            lambda: 'return id(relay_a).state == false;'
                          then:
                            - script.execute: a_on_action
                          else:
                            - script.execute: a_off_action
                      - switch.toggle: relay_a
                    else:
                      # Decoupled mode: only toggle virtual state (triggers HA actions)
                      - switch.toggle: button_a_state

script:
  # Home Assistant service integration scripts
  # These handle cooldown logic to prevent excessive API calls
  - id: a_on_action
    then:
      - if:
          condition:
            and:
              # Standard cooldown check
              - lambda: 'return (millis() - id(last_ha_action_ms_a)) >= ${ha_action_cooldown_ms};'
              # Service configuration check
              - lambda: 'return std::string("${button_a_on_service}") != "" && std::string("${button_a_on_entity}") != "";'
              # Feedback loop protection - don't call HA if recent external change detected
              - lambda: 'return (millis() - id(last_external_change_ms_a)) >= ${feedback_loop_protection_ms};'
          then:
            - lambda: |-
                id(last_ha_action_ms_a) = millis();
                ESP_LOGD("ha_service", "Calling HA service: ${button_a_on_service} on ${button_a_on_entity}");
            - homeassistant.service:
                service: "${button_a_on_service}"
                data:
                  entity_id: "${button_a_on_entity}"
          else:
            - lambda: |-
                ESP_LOGW("ha_service", "HA service call blocked - cooldown or feedback protection active");

  - id: a_off_action
    then:
      - if:
          condition:
            and:
              # Standard cooldown check
              - lambda: 'return (millis() - id(last_ha_action_ms_a)) >= ${ha_action_cooldown_ms};'
              # Service configuration check
              - lambda: 'return std::string("${button_a_off_service}") != "" && std::string("${button_a_off_entity}") != "";'
              # Feedback loop protection - don't call HA if recent external change detected
              - lambda: 'return (millis() - id(last_external_change_ms_a)) >= ${feedback_loop_protection_ms};'
          then:
            - lambda: |-
                id(last_ha_action_ms_a) = millis();
                ESP_LOGD("ha_service", "Calling HA service: ${button_a_off_service} on ${button_a_off_entity}");
            - homeassistant.service:
                service: "${button_a_off_service}"
                data:
                  entity_id: "${button_a_off_entity}"
          else:
            - lambda: |-
                ESP_LOGW("ha_service", "HA service call blocked - cooldown or feedback protection active");

  # Double-click gesture: calls HA service without cooldown (less frequent)
  - id: a_double_action
    then:
      - if:
          condition:
            lambda: 'return std::string("${button_a_double_service}") != "" && std::string("${button_a_double_entity}") != "";'
          then:
            - homeassistant.service:
                service: "${button_a_double_service}"
                data:
                  entity_id: "${button_a_double_entity}"

  # Hold gesture: calls HA service without cooldown (repeating action)
  - id: a_hold_action
    then:
      - if:
          condition:
            lambda: 'return std::string("${button_a_hold_service}") != "" && std::string("${button_a_hold_entity}") != "";'
          then:
            - homeassistant.service:
                service: "${button_a_hold_service}"
                data:
                  entity_id: "${button_a_hold_entity}"
