substitutions:
  device_friendly_name: "Entrance light switch 2"
  device_name: "entrance-light-switch-2"

  button_a_on_service: ""
  button_a_on_entity: ""

  button_a_off_service: ""
  button_a_off_entity: ""

  button_a_hold_service: ""
  button_a_hold_entity: ""

  default_mode_a: "Coupled"
  default_relay_a_target_mode: "Off"
  role: "master"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s
