substitutions:
  device_friendly_name: "Entrance light switch 1"
  device_name: "entrance-light-switch-1"

  # Slave forwards actions to the master. Leave empty on the slave
  button_a_on_service: ""
  button_a_on_entity: ""

  button_a_off_service: ""
  button_a_off_entity: ""

  button_a_hold_service: ""
  button_a_hold_entity: ""

  default_mode_a: "Decoupled"
  default_relay_a_target_mode: "Off"
  role: "slave"
  master_entity_base: "entrance_light_switch_2"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s
