substitutions:
  device_friendly_name: "Hallway light switch"
  device_name: "hallway-light-switch"

  channel_a_on_service: "light.turn_on"
  channel_a_on_entity: "light.hallway_ceiling_light"

  channel_a_off_service: "light.turn_off"
  channel_a_off_entity: "light.hallway_ceiling_light"

  channel_a_hold_service: ""
  channel_a_hold_entity: ""

  default_channel_a_mode: "Decoupled"
  default_channel_a_relay_target_mode: "On"

  sht4x_present: "on"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files: ${["switchman_m5_1_gang.yaml", "switchman_m5_sht4x.yaml"] if sht4x_present != "off" else ["switchman_m5_1_gang.yaml"]}
    refresh: 0s
