substitutions:
  device_friendly_name: "Hallway light switch"
  device_name: "hallway-light-switch"

  button_a_on_service: "light.turn_on"
  button_a_on_entity: "light.hallway_ceiling_light"

  button_a_off_service: "light.turn_off"
  button_a_off_entity: "light.hallway_ceiling_light"

  button_a_hold_service: ""
  button_a_hold_entity: ""

  default_mode_a: "Decoupled"
  default_relay_a_target_mode: "On"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s