substitutions:
  device_friendly_name: "Living room light switch 1"
  device_name: "living-room-light-switch-1"

  button_a_on_service: ""
  button_a_on_entity: ""

  button_a_off_service: ""
  button_a_off_entity: ""

  button_a_hold_service: "light.turn_off"
  button_a_hold_entity: "light.living_room_lights"

  default_mode_a: "Coupled"
  default_relay_a_target_mode: "Off"
  role: "master"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s