substitutions:
  device_friendly_name: "Office light switch 1"
  device_name: "office-light-switch-1"

  button_a_on_service: ""
  button_a_on_entity: ""

  button_a_off_service: ""
  button_a_off_entity: ""

  button_a_hold_service: "switch.turn_off"
  button_a_hold_entity: "switch.office_light_group"

  default_mode_a: "Coupled"
  default_relay_a_target_mode: "Off"

  device_ip: ""

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s