substitutions:
  device_friendly_name: "Outdoor light switch"
  device_name: "outdoor-light-switch"

  channel_a_on_service: "light.turn_on"
  channel_a_on_entity: "light.exterior_lights"

  channel_a_off_service: "light.turn_off"
  channel_a_off_entity: "light.exterior_lights"

  channel_a_hold_service: ""
  channel_a_hold_entity: ""

  default_channel_a_mode: "Coupled"
  default_channel_a_relay_target_mode: "Off"

  channel_b_on_service: "scene.turn_on"
  channel_b_on_entity: "scene.not_at_home"

  channel_b_off_service: "scene.turn_on"
  channel_b_off_entity: "scene.at_home"

  channel_b_hold_service: "switch.toggle"
  channel_b_hold_entity: "switch.robot_vacuum_cleaner_switch"

  default_channel_b_mode: "Decoupled"
  default_channel_b_relay_target_mode: "Off"

  sht4x_present: true

  sht4x_remote_package: "github://bitosome/esphome-sonoff/switchman_m5_sht4x.yaml@main"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_2_gang.yaml
    refresh: 0s
  sht4x_package: ${sht4x_remote_package if sht4x_present else {}}
