substitutions:
  device_friendly_name: "Storeroom light switch"
  device_name: "storeroom-light-switch"

  channel_a_on_service: ""
  channel_a_on_entity: ""

  channel_a_off_service: ""
  channel_a_off_entity: ""

  channel_a_hold_service: ""
  channel_a_hold_entity: ""

  default_channel_a_mode: "Coupled"
  default_channel_a_relay_target_mode: "Off"

  sht4x_present: true

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files: ${["switchman_m5_1_gang.yaml", "switchman_m5_sht4x.yaml"] if sht4x_present else ["switchman_m5_1_gang.yaml"]}
    refresh: 0s
