substitutions:
  device_friendly_name: "WC 2 light switch 2"
  device_name: "wc-2-light-switch-2"

  channel_a_on_service: ""
  channel_a_on_entity: ""

  channel_a_off_service: ""
  channel_a_off_entity: ""

  channel_a_hold_service: "light.turn_off"
  channel_a_hold_entity: "light.wc_2_lights"

  default_channel_a_mode: "Coupled"
  default_channel_a_relay_target_mode: "Off"
  role: "master"

  sht4x_present: "on"

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files: ${["switchman_m5_1_gang.yaml", "switchman_m5_sht4x.yaml"] if sht4x_present != "off" else ["switchman_m5_1_gang.yaml"]}
    refresh: 0s
