substitutions:
  device_friendly_name: "Entrance light switch 1"
  device_name: "entrance-light-switch-1"

  button_a_on_service: "switch.turn_on"
  button_a_on_entity: "switch.entrance_light_switch_group"
  
  button_a_off_service: "switch.turn_off"
  button_a_off_entity: "switch.entrance_light_switch_group"

  button_a_double_service: ""
  button_a_double_entity: ""

  button_a_hold_service: ""
  button_a_hold_entity: ""

  default_mode_a: "Decoupled"
  default_relay_a_target_mode: "Off"

  device_ip: ""

  # Secrets
  api_key: !secret api_key
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  ap_password: !secret ap_password

packages:
  remote_package:
    url: https://github.com/bitosome/esphome-sonoff
    ref: main
    files:
      - switchman_m5_1_gang.yaml
    refresh: 0s